# permissions for end users to edit wbcsnapshots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: wbcsnapshot-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: wbc-operator
    app.kubernetes.io/part-of: wbc-operator
    app.kubernetes.io/managed-by: kustomize
  name: wbcsnapshot-editor-role
rules:
- apiGroups:
  - snapshot.wbc.com
  resources:
  - wbcsnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - snapshot.wbc.com
  resources:
  - wbcsnapshots/status
  verbs:
  - get
