apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test
spec:
  capacity:
   storage: 10Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/tmp/wbc-test-dest"
  storageClassName: manual